# Generated by Django 5.2 on 2025-04-19 09:18

import otp.models.base_otp_model
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthOTPModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=256, verbose_name='code')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='attempts')),
                ('max_attempts', models.PositiveIntegerField(default=3, verbose_name='max attempts')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('is_verified', models.BooleanField(default=False, verbose_name='is verified')),
                ('expires_at', models.DateTimeField(default=otp.models.base_otp_model.get_default_expires_at, verbose_name='expires at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('last_attempted', models.DateTimeField(auto_now=True, verbose_name='last attempted')),
                ('ip_address', models.GenericIPAddressField()),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Auth OTP code',
                'verbose_name_plural': 'Auth OTP codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
