# Generated by Django 5.2 on 2025-04-19 10:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthAttemptModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auth_type', models.CharField(choices=[('login', 'Login'), ('registration', 'Registration')], max_length=12)),
                ('ip_address', models.GenericIPAddressField()),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_attempted', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Auth attempt',
                'verbose_name_plural': 'Auth attempts',
                'ordering': ['-created_at'],
            },
        ),
    ]
