# Generated by Django 5.2 on 2025-04-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authattemptmodel',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
