# Generated by Django 5.2 on 2025-04-19 12:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_authattemptmodel_is_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationOTPModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=256)),
                ('is_used', models.BooleanField(default=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_attempted', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'verbose_name': 'Registration OTP code',
                'verbose_name_plural': 'Registration OTP codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
